import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

export interface SyncFrontmatter {
  title: string;
  description: string;
  sidebar_order: number;
  sidebar_group: "GETTING STARTED" | "CORE CONCEPTS" | "USING GATEHOUSE" | "REFERENCE";
}

export interface SyncDocOptions {
  src: string;
  dst: string;
  frontmatter: SyncFrontmatter;
}

function escapeYamlString(value: string): string {
  return value.replace(/"/g, '\\"');
}

function stripLeadingH1(markdown: string): string {
  return markdown.replace(/^\s*#\s+[^\n]*\n+/, "");
}

export function syncDoc(opts: SyncDocOptions): void {
  const raw = readFileSync(opts.src, "utf8");
  const body = stripLeadingH1(raw);

  const fm = opts.frontmatter;
  const yaml = [
    "---",
    `title: "${escapeYamlString(fm.title)}"`,
    `description: "${escapeYamlString(fm.description)}"`,
    `sidebar_order: ${fm.sidebar_order}`,
    `sidebar_group: "${fm.sidebar_group}"`,
    "---",
    "",
    "{/* Synced from canonical markdown. Do not edit this file directly. */}",
    "",
  ].join("\n");

  mkdirSync(dirname(opts.dst), { recursive: true });
  writeFileSync(opts.dst, yaml + body, "utf8");
}

// Run from the CLI: sync the canonical docs files into the content collection
if (import.meta.main) {
  const siteRoot = new URL("..", import.meta.url).pathname;
  const repoRoot = new URL("../..", import.meta.url).pathname;

  syncDoc({
    src: `${repoRoot}docs/agent-api-reference.md`,
    dst: `${siteRoot}src/content/docs/for-agents.mdx`,
    frontmatter: {
      title: "For Agents",
      description: "Agent-facing API reference for Gatehouse: auth, secret access, proxy mode, dynamic secrets, errors.",
      sidebar_order: 3,
      sidebar_group: "REFERENCE",
    },
  });

  syncDoc({
    src: `${repoRoot}docs/integrations.md`,
    dst: `${siteRoot}src/content/docs/integrations.mdx`,
    frontmatter: {
      title: "Integrations",
      description: "How to wire Gatehouse into agent harnesses: Claude Code, Codex, Cursor, Windsurf, and more.",
      sidebar_order: 4,
      sidebar_group: "REFERENCE",
    },
  });

  console.log("sync-docs: wrote for-agents.mdx and integrations.mdx");
}
